### PR TITLE
Fix bare except warning

### LINKED ISSUE #127: `BareExcept` supposed-fix undermines library user's ability to globally disable `BareExcept`
https://github.com/status-im/nimbus-eth2/pull/4660#issuecomment-1444385841

When taking a version of `nimbus-eth2` which globally disables `BareExcept` in `config.nims`, and bumping to current `master` of this repository:
```
nimbus-eth2/vendor/nim-websock/websock/websock.nim(258, 5) template/generic instantiation of `async` from here
nimbus-eth2/vendor/nim-websock/websock/websock.nim(256, 34) template/generic instantiation of `futureContinue` from here
nimbus-eth2/vendor/nim-chronos/chronos/asyncfutures2.nim(389, 3) Warning: catch a more precise Exception deriving from CatchableError or Defect. [BareExcept]
nimbus-eth2/vendor/nim-websock/websock/websock.nim(258, 5) template/generic instantiation of `async` from here
nimbus-eth2/vendor/nim-websock/websock/websock.nim(256, 34) template/generic instantiation of `futureContinue` from here
nimbus-eth2/vendor/nim-chronos/chronos/asyncfutures2.nim(389, 3) Warning: catch a more precise Exception deriving from CatchableError or Defect. [BareExcept]
nimbus-eth2/vendor/nim-websock/websock/http/client.nim(42, 76) template/generic instantiation of `async` from here
nimbus-eth2/vendor/nim-chronos/chronos/asyncfutures2.nim(389, 3) Warning: catch a more precise Exception deriving from CatchableError or Defect. [BareExcept]
nimbus-eth2/vendor/nim-websock/websock/http/server.nim(48, 51) template/generic instantiation of `async` from here
nimbus-eth2/vendor/nim-chronos/chronos/asyncfutures2.nim(389, 3) Warning: catch a more precise Exception deriving from CatchableError or Defect. [BareExcept]
nimbus-eth2/vendor/nim-websock/websock/http/server.nim(67, 47) template/generic instantiation of `async` from here
nimbus-eth2/vendor/nim-chronos/chronos/asyncfutures2.nim(389, 3) Warning: catch a more precise Exception deriving from CatchableError or Defect. [BareExcept]
nimbus-eth2/vendor/nim-websock/websock/http/client.nim(42, 76) template/generic instantiation of `async` from here
nimbus-eth2/vendor/nim-chronos/chronos/asyncfutures2.nim(389, 3) Warning: catch a more precise Exception deriving from CatchableError or Defect. [BareExcept]
nimbus-eth2/vendor/nim-websock/websock/http/server.nim(48, 51) template/generic instantiation of `async` from here
nimbus-eth2/vendor/nim-chronos/chronos/asyncfutures2.nim(389, 3) Warning: catch a more precise Exception deriving from CatchableError or Defect. [BareExcept]
nimbus-eth2/vendor/nim-websock/websock/http/server.nim(67, 47) template/generic instantiation of `async` from here
nimbus-eth2/vendor/nim-chronos/chronos/asyncfutures2.nim(389, 3) Warning: catch a more precise Exception deriving from CatchableError or Defect. [BareExcept]
nimbus-eth2/vendor/nim-websock/websock/websock.nim(258, 5) template/generic instantiation of `async` from here
nimbus-eth2/vendor/nim-websock/websock/websock.nim(256, 34) template/generic instantiation of `futureContinue` from here
nimbus-eth2/vendor/nim-chronos/chronos/asyncfutures2.nim(389, 3) Warning: catch a more precise Exception deriving from CatchableError or Defect. [BareExcept]
```

### PR DESCRIPTION
**Pull request by Menduist**
Fix #127

### CODE REVIEW

File: chronicles.nim [hunk 1]
```diff
@@ -346,12 +346,12 @@ template log*(lineInfo: static InstInfo,
 template wrapSideEffects(debug: bool, body: untyped) {.inject.} =
   when debug:
     {.noSideEffect.}:
-      when (NimMajor, NimMinor) >= (1, 6):
-        {.warning[BareExcept]:off.}
+      when defined(nimHasWarnBareExcept):
+        {.push warning[BareExcept]:off.}
```
Comment (arnetheduck) [inline chronicles.nim:350]: are bareexcept warnings on or off in the `body`, with this construct?

Comment (arnetheduck) [reply chronicles.nim:350]: see also https://github.com/nim-lang/Nim/pull/21390

Comment (Menduist) [reply chronicles.nim:350]: Off, thought I don't expect it to be an issue in this case, unless someone does
```nim
debug hehe=try: echo "hey" expect: discard
```
